# config
SR = 16000
TIME = 5
MAX_LENGTH = SR * TIME
MIN_LENGTH = 2**14
DATA_DIR = './data'
CLEAN_AUDIO_DIR = DATA_DIR + '/clean'
NOISY_AUDIO_DIR = DATA_DIR + '/noisy'
DISTORTED_AUDIO_DIR = DATA_DIR + '/distorted'
FILTERED_AUDIO_DIR = DATA_DIR + '/filtered'
IMG_DIR = './img'
DIRS = [CLEAN_AUDIO_DIR, NOISY_AUDIO_DIR,
        DISTORTED_AUDIO_DIR, FILTERED_AUDIO_DIR]
CLIPPING_FACTOR = 0.1
TEST_SIZE = 0.2
DATASET_SIZE = 3000
CONFIG_INFO = {"Sample Rate": SR, "Time": TIME, "Max Length": MAX_LENGTH,
               "Clipping Factor": CLIPPING_FACTOR, "Test Size": TEST_SIZE, "Dataset Size": DATASET_SIZE}
N_MELS = 256
PIX2PIX_SHAPE = (256, 256)
